	<option class="AF">Afghanistan</option>
	<option class="AX">Åland Islands</option>
	<option class="AL">Albania</option>
	<option class="DZ">Algeria</option>
	<option class="AS">American Samoa</option>
	<option class="AD">Andorra</option>
	<option class="AO">Angola</option>
	<option class="AI">Anguilla</option>
	<option class="AQ">Antarctica</option>
	<option class="AG">Antigua and Barbuda</option>
	<option class="AR">Argentina</option>
	<option class="AM">Armenia</option>
	<option class="AW">Aruba</option>
	<option class="AU">Australia</option>
	<option class="AT">Austria</option>
	<option class="AZ">Azerbaijan</option>
	<option class="BS">Bahamas</option>
	<option class="BH">Bahrain</option>
	<option class="BD">Bangladesh</option>
	<option class="BB">Barbados</option>
	<option class="BY">Belarus</option>
	<option class="BE">Belgium</option>
	<option class="BZ">Belize</option>
	<option class="BJ">Benin</option>
	<option class="BM">Bermuda</option>
	<option class="BT">Bhutan</option>
	<option class="BO">Bolivia, Plurinational State of</option>
	<option class="BQ">Bonaire, Sint Eustatius and Saba</option>
	<option class="BA">Bosnia and Herzegovina</option>
	<option class="BW">Botswana</option>
	<option class="BV">Bouvet Island</option>
	<option class="BR">Brazil</option>
	<option class="IO">British Indian Ocean Territory</option>
	<option class="BN">Brunei Darussalam</option>
	<option class="BG">Bulgaria</option>
	<option class="BF">Burkina Faso</option>
	<option class="BI">Burundi</option>
	<option class="KH">Cambodia</option>
	<option class="CM">Cameroon</option>
	<option class="CA">Canada</option>
	<option class="CV">Cape Verde</option>
	<option class="KY">Cayman Islands</option>
	<option class="CF">Central African Republic</option>
	<option class="TD">Chad</option>
	<option class="CL">Chile</option>
	<option class="CN">China</option>
	<option class="CX">Christmas Island</option>
	<option class="CC">Cocos (Keeling) Islands</option>
	<option class="CO">Colombia</option>
	<option class="KM">Comoros</option>
	<option class="CG">Congo</option>
	<option class="CD">Congo, the Democratic Republic of the</option>
	<option class="CK">Cook Islands</option>
	<option class="CR">Costa Rica</option>
	<option class="CI">Côte d'Ivoire</option>
	<option class="HR">Croatia</option>
	<option class="CU">Cuba</option>
	<option class="CW">Curaçao</option>
	<option class="CY">Cyprus</option>
	<option class="CZ">Czech Republic</option>
	<option class="DK">Denmark</option>
	<option class="DJ">Djibouti</option>
	<option class="DM">Dominica</option>
	<option class="DO">Dominican Republic</option>
	<option class="EC">Ecuador</option>
	<option class="EG">Egypt</option>
	<option class="SV">El Salvador</option>
	<option class="GQ">Equatorial Guinea</option>
	<option class="ER">Eritrea</option>
	<option class="EE">Estonia</option>
	<option class="ET">Ethiopia</option>
	<option class="FK">Falkland Islands (Malvinas)</option>
	<option class="FO">Faroe Islands</option>
	<option class="FJ">Fiji</option>
	<option class="FI">Finland</option>
	<option class="FR">France</option>
	<option class="GF">French Guiana</option>
	<option class="PF">French Polynesia</option>
	<option class="TF">French Southern Territories</option>
	<option class="GA">Gabon</option>
	<option class="GM">Gambia</option>
	<option class="GE">Georgia</option>
	<option class="DE">Germany</option>
	<option class="GH">Ghana</option>
	<option class="GI">Gibraltar</option>
	<option class="GR">Greece</option>
	<option class="GL">Greenland</option>
	<option class="GD">Grenada</option>
	<option class="GP">Guadeloupe</option>
	<option class="GU">Guam</option>
	<option class="GT">Guatemala</option>
	<option class="GG">Guernsey</option>
	<option class="GN">Guinea</option>
	<option class="GW">Guinea-Bissau</option>
	<option class="GY">Guyana</option>
	<option class="HT">Haiti</option>
	<option class="HM">Heard Island and McDonald Islands</option>
	<option class="VA">Holy See (Vatican City State)</option>
	<option class="HN">Honduras</option>
	<option class="HK">Hong Kong</option>
	<option class="HU">Hungary</option>
	<option class="IS">Iceland</option>
	<option class="IN">India</option>
	<option class="ID">Indonesia</option>
	<option class="IR">Iran, Islamic Republic of</option>
	<option class="IQ">Iraq</option>
	<option class="IE">Ireland</option>
	<option class="IM">Isle of Man</option>
	<option class="IL">Israel</option>
	<option class="IT">Italy</option>
	<option class="JM">Jamaica</option>
	<option class="JP">Japan</option>
	<option class="JE">Jersey</option>
	<option class="JO">Jordan</option>
	<option class="KZ">Kazakhstan</option>
	<option class="KE">Kenya</option>
	<option class="KI">Kiribati</option>
	<option class="KP">Korea, Democratic People's Republic of</option>
	<option class="KR">Korea, Republic of</option>
	<option class="KW">Kuwait</option>
	<option class="KG">Kyrgyzstan</option>
	<option class="LA">Lao People's Democratic Republic</option>
	<option class="LV">Latvia</option>
	<option class="LB">Lebanon</option>
	<option class="LS">Lesotho</option>
	<option class="LR">Liberia</option>
	<option class="LY">Libya</option>
	<option class="LI">Liechtenstein</option>
	<option class="LT">Lithuania</option>
	<option class="LU">Luxembourg</option>
	<option class="MO">Macao</option>
	<option class="MK">Macedonia, the former Yugoslav Republic of</option>
	<option class="MG">Madagascar</option>
	<option class="MW">Malawi</option>
	<option class="MY">Malaysia</option>
	<option class="MV">Maldives</option>
	<option class="ML">Mali</option>
	<option class="MT">Malta</option>
	<option class="MH">Marshall Islands</option>
	<option class="MQ">Martinique</option>
	<option class="MR">Mauritania</option>
	<option class="MU">Mauritius</option>
	<option class="YT">Mayotte</option>
	<option class="MX">Mexico</option>
	<option class="FM">Micronesia, Federated States of</option>
	<option class="MD">Moldova, Republic of</option>
	<option class="MC">Monaco</option>
	<option class="MN">Mongolia</option>
	<option class="ME">Montenegro</option>
	<option class="MS">Montserrat</option>
	<option class="MA">Morocco</option>
	<option class="MZ">Mozambique</option>
	<option class="MM">Myanmar</option>
	<option class="NA">Namibia</option>
	<option class="NR">Nauru</option>
	<option class="NP">Nepal</option>
	<option class="NL">Netherlands</option>
	<option class="NC">New Caledonia</option>
	<option class="NZ">New Zealand</option>
	<option class="NI">Nicaragua</option>
	<option class="NE">Niger</option>
	<option class="NG">Nigeria</option>
	<option class="NU">Niue</option>
	<option class="NF">Norfolk Island</option>
	<option class="MP">Northern Mariana Islands</option>
	<option class="NO">Norway</option>
	<option class="OM">Oman</option>
	<option class="PK">Pakistan</option>
	<option class="PW">Palau</option>
	<option class="PS">Palestinian Territory, Occupied</option>
	<option class="PA">Panama</option>
	<option class="PG">Papua New Guinea</option>
	<option class="PY">Paraguay</option>
	<option class="PE">Peru</option>
	<option class="PH">Philippines</option>
	<option class="PN">Pitcairn</option>
	<option class="PL">Poland</option>
	<option class="PT">Portugal</option>
	<option class="PR">Puerto Rico</option>
	<option class="QA">Qatar</option>
	<option class="RE">Réunion</option>
	<option class="RO">Romania</option>
	<option class="RU">Russian Federation</option>
	<option class="RW">Rwanda</option>
	<option class="BL">Saint Barthélemy</option>
	<option class="SH">Saint Helena, Ascension and Tristan da Cunha</option>
	<option class="KN">Saint Kitts and Nevis</option>
	<option class="LC">Saint Lucia</option>
	<option class="MF">Saint Martin (French part)</option>
	<option class="PM">Saint Pierre and Miquelon</option>
	<option class="VC">Saint Vincent and the Grenadines</option>
	<option class="WS">Samoa</option>
	<option class="SM">San Marino</option>
	<option class="ST">Sao Tome and Principe</option>
	<option class="SA">Saudi Arabia</option>
	<option class="SN">Senegal</option>
	<option class="RS">Serbia</option>
	<option class="SC">Seychelles</option>
	<option class="SL">Sierra Leone</option>
	<option class="SG">Singapore</option>
	<option class="SX">Sint Maarten (Dutch part)</option>
	<option class="SK">Slovakia</option>
	<option class="SI">Slovenia</option>
	<option class="SB">Solomon Islands</option>
	<option class="SO">Somalia</option>
	<option class="ZA">South Africa</option>
	<option class="GS">South Georgia and the South Sandwich Islands</option>
	<option class="SS">South Sudan</option>
	<option class="ES">Spain</option>
	<option class="LK">Sri Lanka</option>
	<option class="SD">Sudan</option>
	<option class="SR">Suriname</option>
	<option class="SJ">Svalbard and Jan Mayen</option>
	<option class="SZ">Swaziland</option>
	<option class="SE">Sweden</option>
	<option class="CH">Switzerland</option>
	<option class="SY">Syrian Arab Republic</option>
	<option class="TW">Taiwan, Province of China</option>
	<option class="TJ">Tajikistan</option>
	<option class="TZ">Tanzania, United Republic of</option>
	<option class="TH">Thailand</option>
	<option class="TL">Timor-Leste</option>
	<option class="TG">Togo</option>
	<option class="TK">Tokelau</option>
	<option class="TO">Tonga</option>
	<option class="TT">Trinidad and Tobago</option>
	<option class="TN">Tunisia</option>
	<option class="TR">Turkey</option>
	<option class="TM">Turkmenistan</option>
	<option class="TC">Turks and Caicos Islands</option>
	<option class="TV">Tuvalu</option>
	<option class="UG">Uganda</option>
	<option class="UA">Ukraine</option>
	<option class="AE">United Arab Emirates</option>
	<option class="GB">United Kingdom</option>
	<option class="US">United States</option>
	<option class="UM">United States Minor Outlying Islands</option>
	<option class="UY">Uruguay</option>
	<option class="UZ">Uzbekistan</option>
	<option class="VU">Vanuatu</option>
	<option class="VE">Venezuela, Bolivarian Republic of</option>
	<option class="VN">Viet Nam</option>
	<option class="VG">Virgin Islands, British</option>
	<option class="VI">Virgin Islands, U.S.</option>
	<option class="WF">Wallis and Futuna</option>
	<option class="EH">Western Sahara</option>
	<option class="YE">Yemen</option>
	<option class="ZM">Zambia</option>
	<option class="ZW">Zimbabwe</option>